bind_port = 8086
bind_host = "127.0.0.1"

service_id = "hulygram"
kvs_namespace = "hulygram"
outbound_tx_topic = "hulygun"
inbound_tx_topic = "cockroach.tx"
allowed_dialog_ids = "4982993114,4937631480,1044298783,1974697595"
get_file_rate_limit = 5
sync_process_limit = 30
sync_process_limit_local = 5
get_history_rate_limit = 3000

blob_service_path = "http://localhost:4030"
base_url = "https://hulygram.aristov.cc"
dry_run = false

redis_urls = "redis://127.0.0.1:6379"
redis_password = "<invalid>"
redis_mode = "direct"
redis_service = "mymaster"
